### ISSUE TITLE
Image Loading 

### ISSUE THREAD

**Issue by Titalah** [Tibo-s-Team/OCR_EPITA#8]
Our OCR should load images (with paths) and ready them.
This means reading the image and creating a usable RGB matrix for preprocessing.

**Comment by d4ilyrun** [comment]
I'm implementing the matrix after the color supression process instead, that way you only have to store values of 0 or 1 making the process easier.

**Comment by d4ilyrun** [comment]
(#15) - Image loaded succesfully.
